<%@ Page Language="C#" Title="SearchOrder" AutoEventWireup="true" EnableSessionState="True" CodeBehind="SearchOrder.aspx.cs" Inherits="GalaxyLottoWeb.Pages.SearchOrder" %>

<!DOCTYPE html>

<html lang='zh-tw' xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><%:Page.Title %></title>
    <meta name="viewport" content='width=device-width, initial-scale=1' />
    <webopt:BundleReference runat="server" Path="~/Content/css" />
    <%--<link rel='stylesheet' href='../Content/bootstrap.css' />--%>
    <%--<link rel='stylesheet' href='../Content/site.css' />--%>
    <%--<link rel='stylesheet' href='../Content/galaxylotto.css' />--%>
    <%--<script src="../Scripts/jquery-3.1.1.min.js"></script>--%>
    <%--<script src="../Scripts/bootstrap.js"></script>--%>
    <link href="SearchOrder1.ico" rel="shortcut icon" type="image/x-icon" />
</head>
<body id="body" class="glbody">
    <form runat="server">
        <asp:ScriptManager runat="server">
            <Scripts>
                <asp:ScriptReference Name="jquery" />
                <asp:ScriptReference Name="bootstrap" />
                <asp:ScriptReference Name="glScript" />
            </Scripts>
        </asp:ScriptManager>
        <asp:Timer ID="Timer1" OnTick="Timer1Tick" runat="server" Interval="5000" Enabled="true" />
        <asp:UpdateProgress ID="UpdateProgress1" AssociatedUpdatePanelID="UpSearchOrder" runat="server">
            <ProgressTemplate>
                <asp:Image ID="imgProgress" runat="server" AlternateText="progress" ImageUrl="loader.gif" Width="32" />
                Processing...           
            </ProgressTemplate>
        </asp:UpdateProgress>

        <asp:UpdatePanel ID="UpSearchOrder" runat="server">
            <Triggers>
                <asp:AsyncPostBackTrigger ControlID="Timer1" EventName="Tick" />
            </Triggers>
            <ContentTemplate>
                <asp:Panel ID="pnlinfo" runat="server" Width="100%" ScrollBars="Auto" Direction="LeftToRight" HorizontalAlign="Center" BackColor="Black" ForeColor="White">
                    <asp:Button ID="btnClose" runat="server" Text="關閉(C)" AccessKey="c" OnClientClick="window.close();" TabIndex="1" BackColor="Black" ForeColor="LightPink" BorderColor="LightPink" BorderWidth="1" ToolTip="Close" />
                    <asp:Button ID="btnRestart" runat="server" Text="重啟(R)" AccessKey="r" OnClick="BtnRestartClick" TabIndex="1" BackColor="Black" ForeColor="LightBlue" BorderColor="LightBlue" BorderWidth="1" />
                    <asp:Button ID="btnClear" runat="server" Text="清空(M)" AccessKey="m" OnClick="BtnClearClick" TabIndex="1" BackColor="Black" ForeColor="LightGreen" BorderColor="LightGreen" BorderWidth="1" />
                    <asp:CheckBox ID="chkStart" runat="server" Text="啟動(S)" AccessKey="s" TextAlign="Right" AutoPostBack="true" CssClass="glcheck" />
                    <asp:Label runat="server" ID="lblTitle" Font-Size="Small" />
                    <asp:Label ID="lblArgument00" runat="server" Font-Size="Small" ForeColor="LightGreen" />
                </asp:Panel>
                <asp:Panel ID="pnlDetail" runat="server" CssClass="glColumn750" Height="850" EnableViewState="true" ViewStateMode="Enabled">
                    <asp:GridView ID="gvSearchOrder" runat="server" CssClass="gltable" GridLines="Horizontal"
                        AutoGenerateColumns="true" AutoGenerateDeleteButton="true" />
                </asp:Panel>
            </ContentTemplate>
        </asp:UpdatePanel>
    </form>
</body>
</html>
