//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxyLottoWeb.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GalaxyLottoWeb.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        public static System.Drawing.Icon analyst {
            get {
                object obj = ResourceManager.GetObject("analyst", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 遞增 的當地語系化字串。
        /// </summary>
        public static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap bgFlower {
            get {
                object obj = ResourceManager.GetObject("bgFlower", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap bgGreen {
            get {
                object obj = ResourceManager.GetObject("bgGreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap bgKid {
            get {
                object obj = ResourceManager.GetObject("bgKid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap bgUpdate {
            get {
                object obj = ResourceManager.GetObject("bgUpdate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap bgYellowflowers {
            get {
                object obj = ResourceManager.GetObject("bgYellowflowers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Big {
            get {
                object obj = ResourceManager.GetObject("Big", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap btnclose00 {
            get {
                object obj = ResourceManager.GetObject("btnclose00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap btnclose01 {
            get {
                object obj = ResourceManager.GetObject("btnclose01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap btnclose02 {
            get {
                object obj = ResourceManager.GetObject("btnclose02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap btnclose03 {
            get {
                object obj = ResourceManager.GetObject("btnclose03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap btnCloseRedBig {
            get {
                object obj = ResourceManager.GetObject("btnCloseRedBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap btnCloseRedSmall {
            get {
                object obj = ResourceManager.GetObject("btnCloseRedSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap btnCopy {
            get {
                object obj = ResourceManager.GetObject("btnCopy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap btnDownarrow {
            get {
                object obj = ResourceManager.GetObject("btnDownarrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap btnFilecabinet {
            get {
                object obj = ResourceManager.GetObject("btnFilecabinet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap btnFullView {
            get {
                object obj = ResourceManager.GetObject("btnFullView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap btnHelp {
            get {
                object obj = ResourceManager.GetObject("btnHelp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap BtnHelp01 {
            get {
                object obj = ResourceManager.GetObject("BtnHelp01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap btnList {
            get {
                object obj = ResourceManager.GetObject("btnList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        public static System.Drawing.Icon btnList1 {
            get {
                object obj = ResourceManager.GetObject("btnList1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap btnMaxBlue {
            get {
                object obj = ResourceManager.GetObject("btnMaxBlue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap btnMinBlue {
            get {
                object obj = ResourceManager.GetObject("btnMinBlue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap btnMinBlue01 {
            get {
                object obj = ResourceManager.GetObject("btnMinBlue01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似  &gt;&gt;  的當地語系化字串。
        /// </summary>
        public static string btnNext10Page {
            get {
                return ResourceManager.GetString("btnNext10Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下十頁 的當地語系化字串。
        /// </summary>
        public static string btnNext10PageTip {
            get {
                return ResourceManager.GetString("btnNext10PageTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  &gt;  的當地語系化字串。
        /// </summary>
        public static string btnNextPage {
            get {
                return ResourceManager.GetString("btnNextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下一頁 的當地語系化字串。
        /// </summary>
        public static string btnNextPageTip {
            get {
                return ResourceManager.GetString("btnNextPageTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  &lt;&lt;  的當地語系化字串。
        /// </summary>
        public static string btnPrev10Page {
            get {
                return ResourceManager.GetString("btnPrev10Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上十頁 的當地語系化字串。
        /// </summary>
        public static string btnPrev10PageTip {
            get {
                return ResourceManager.GetString("btnPrev10PageTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似  &lt;  的當地語系化字串。
        /// </summary>
        public static string btnPrevPage {
            get {
                return ResourceManager.GetString("btnPrevPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上一頁 的當地語系化字串。
        /// </summary>
        public static string btnPrevPageTip {
            get {
                return ResourceManager.GetString("btnPrevPageTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap btnRelation {
            get {
                object obj = ResourceManager.GetObject("btnRelation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap btnSearch {
            get {
                object obj = ResourceManager.GetObject("btnSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap btnSettings {
            get {
                object obj = ResourceManager.GetObject("btnSettings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap btnUp {
            get {
                object obj = ResourceManager.GetObject("btnUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap btnUparrow {
            get {
                object obj = ResourceManager.GetObject("btnUparrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap btnUpdate {
            get {
                object obj = ResourceManager.GetObject("btnUpdate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap btnUpdate02 {
            get {
                object obj = ResourceManager.GetObject("btnUpdate02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        public static System.Drawing.Icon btnUpdate1 {
            get {
                object obj = ResourceManager.GetObject("btnUpdate1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        public static System.Drawing.Icon Bulb {
            get {
                object obj = ResourceManager.GetObject("Bulb", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Button_Icon_Black {
            get {
                object obj = ResourceManager.GetObject("Button_Icon_Black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Button_Icon_Blue {
            get {
                object obj = ResourceManager.GetObject("Button_Icon_Blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Button_Icon_BlueSky {
            get {
                object obj = ResourceManager.GetObject("Button_Icon_BlueSky", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Button_Icon_Brown {
            get {
                object obj = ResourceManager.GetObject("Button_Icon_Brown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Button_Icon_Cyan {
            get {
                object obj = ResourceManager.GetObject("Button_Icon_Cyan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Button_Icon_Fuchsia {
            get {
                object obj = ResourceManager.GetObject("Button_Icon_Fuchsia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Button_Icon_Green {
            get {
                object obj = ResourceManager.GetObject("Button_Icon_Green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Button_Icon_GreenBlue {
            get {
                object obj = ResourceManager.GetObject("Button_Icon_GreenBlue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Button_Icon_GreenForest {
            get {
                object obj = ResourceManager.GetObject("Button_Icon_GreenForest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Button_Icon_GreenYellow {
            get {
                object obj = ResourceManager.GetObject("Button_Icon_GreenYellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Button_Icon_LightRed {
            get {
                object obj = ResourceManager.GetObject("Button_Icon_LightRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Button_Icon_Lime {
            get {
                object obj = ResourceManager.GetObject("Button_Icon_Lime", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Button_Icon_Orange {
            get {
                object obj = ResourceManager.GetObject("Button_Icon_Orange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Button_Icon_Pink {
            get {
                object obj = ResourceManager.GetObject("Button_Icon_Pink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Button_Icon_Purple {
            get {
                object obj = ResourceManager.GetObject("Button_Icon_Purple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Button_Icon_Red {
            get {
                object obj = ResourceManager.GetObject("Button_Icon_Red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Button_Icon_Turquoise {
            get {
                object obj = ResourceManager.GetObject("Button_Icon_Turquoise", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Button_Icon_Violet {
            get {
                object obj = ResourceManager.GetObject("Button_Icon_Violet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Button_Icon_White {
            get {
                object obj = ResourceManager.GetObject("Button_Icon_White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Button_Icon_Yellow {
            get {
                object obj = ResourceManager.GetObject("Button_Icon_Yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 取消 的當地語系化字串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        public static System.Drawing.Icon Computers {
            get {
                object obj = ResourceManager.GetObject("Computers", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Dafu {
            get {
                object obj = ResourceManager.GetObject("Dafu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 7 的當地語系化字串。
        /// </summary>
        public static string defaultCriticalNumValue {
            get {
                return ResourceManager.GetString("defaultCriticalNumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 0 的當地語系化字串。
        /// </summary>
        public static string defaultDataLimitValue {
            get {
                return ResourceManager.GetString("defaultDataLimitValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 0 的當地語系化字串。
        /// </summary>
        public static string defaultDataOffsetValue {
            get {
                return ResourceManager.GetString("defaultDataOffsetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 50 的當地語系化字串。
        /// </summary>
        public static string defaultDataRowsLimitValue {
            get {
                return ResourceManager.GetString("defaultDataRowsLimitValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 200 的當地語系化字串。
        /// </summary>
        public static string defaultDisplayPeriodValue {
            get {
                return ResourceManager.GetString("defaultDisplayPeriodValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 0 的當地語系化字串。
        /// </summary>
        public static string defaultFilterMaxValue {
            get {
                return ResourceManager.GetString("defaultFilterMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 0 的當地語系化字串。
        /// </summary>
        public static string defaultFilterMinValue {
            get {
                return ResourceManager.GetString("defaultFilterMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 5 的當地語系化字串。
        /// </summary>
        public static string defaultFreqDNALength {
            get {
                return ResourceManager.GetString("defaultFreqDNALength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 30 的當地語系化字串。
        /// </summary>
        public static string defaultHistoryPeriodsValue {
            get {
                return ResourceManager.GetString("defaultHistoryPeriodsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 20 的當地語系化字串。
        /// </summary>
        public static string defaultHistoryTestPeriodsValue {
            get {
                return ResourceManager.GetString("defaultHistoryTestPeriodsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 2 的當地語系化字串。
        /// </summary>
        public static string defaultHitMinValue {
            get {
                return ResourceManager.GetString("defaultHitMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 0 的當地語系化字串。
        /// </summary>
        public static string defaultNextNums {
            get {
                return ResourceManager.GetString("defaultNextNums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1 的當地語系化字串。
        /// </summary>
        public static string defaultNextStep {
            get {
                return ResourceManager.GetString("defaultNextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 0 的當地語系化字串。
        /// </summary>
        public static string defaultSearchLimitValue {
            get {
                return ResourceManager.GetString("defaultSearchLimitValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 20 的當地語系化字串。
        /// </summary>
        public static string defaultSearchLimitValue01 {
            get {
                return ResourceManager.GetString("defaultSearchLimitValue01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 0 的當地語系化字串。
        /// </summary>
        public static string defaultSearchOffsetValue {
            get {
                return ResourceManager.GetString("defaultSearchOffsetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 200 的當地語系化字串。
        /// </summary>
        public static string defaultTargetTestPeriods {
            get {
                return ResourceManager.GetString("defaultTargetTestPeriods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1 的當地語系化字串。
        /// </summary>
        public static string defaultTestPeriodsValue {
            get {
                return ResourceManager.GetString("defaultTestPeriodsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 遞減 的當地語系化字串。
        /// </summary>
        public static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap dot_green_200 {
            get {
                object obj = ResourceManager.GetObject("dot_green_200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap dot_red_200 {
            get {
                object obj = ResourceManager.GetObject("dot_red_200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        public static System.Drawing.Icon Error {
            get {
                object obj = ResourceManager.GetObject("Error", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 篩選 的當地語系化字串。
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Filter_Filled {
            get {
                object obj = ResourceManager.GetObject("Filter_Filled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Filter_NoFilled {
            get {
                object obj = ResourceManager.GetObject("Filter_NoFilled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream Finish {
            get {
                return ResourceManager.GetStream("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream finished {
            get {
                return ResourceManager.GetStream("finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap home {
            get {
                object obj = ResourceManager.GetObject("home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &amp;nbsp; 的當地語系化字串。
        /// </summary>
        public static string HtmlSpace {
            get {
                return ResourceManager.GetString("HtmlSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        public static System.Drawing.Icon icoMain {
            get {
                object obj = ResourceManager.GetObject("icoMain", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap icon_Back {
            get {
                object obj = ResourceManager.GetObject("icon_Back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        public static System.Drawing.Icon Inactive {
            get {
                object obj = ResourceManager.GetObject("Inactive", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap l539 {
            get {
                object obj = ResourceManager.GetObject("l539", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 綜合計算01(G) 的當地語系化字串。
        /// </summary>
        public static string LabelCacul01 {
            get {
                return ResourceManager.GetString("LabelCacul01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 平衡表(G) 的當地語系化字串。
        /// </summary>
        public static string LabelDataB {
            get {
                return ResourceManager.GetString("LabelDataB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 振盪表(G) 的當地語系化字串。
        /// </summary>
        public static string LabelDataN {
            get {
                return ResourceManager.GetString("LabelDataN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 振盪平衡總表01(G) 的當地語系化字串。
        /// </summary>
        public static string LabelDataNBT01 {
            get {
                return ResourceManager.GetString("LabelDataNBT01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 振盪圖(G) 的當地語系化字串。
        /// </summary>
        public static string LabelDataNChart {
            get {
                return ResourceManager.GetString("LabelDataNChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活性表(G) 的當地語系化字串。
        /// </summary>
        public static string LabelFreqActive {
            get {
                return ResourceManager.GetString("LabelFreqActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活性表01(G) 的當地語系化字串。
        /// </summary>
        public static string LabelFreqActive01 {
            get {
                return ResourceManager.GetString("LabelFreqActive01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活性表01總表(G) 的當地語系化字串。
        /// </summary>
        public static string LabelFreqActive01T {
            get {
                return ResourceManager.GetString("LabelFreqActive01T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活性表01R總表(G) 的當地語系化字串。
        /// </summary>
        public static string LabelFreqActive01TR {
            get {
                return ResourceManager.GetString("LabelFreqActive01TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活性表02(G) 的當地語系化字串。
        /// </summary>
        public static string LabelFreqActive02 {
            get {
                return ResourceManager.GetString("LabelFreqActive02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活性表03(G) 的當地語系化字串。
        /// </summary>
        public static string LabelFreqActive03 {
            get {
                return ResourceManager.GetString("LabelFreqActive03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活性圖(G) 的當地語系化字串。
        /// </summary>
        public static string LabelFreqActiveChart {
            get {
                return ResourceManager.GetString("LabelFreqActiveChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活性圖01(G) 的當地語系化字串。
        /// </summary>
        public static string LabelFreqActiveChart01 {
            get {
                return ResourceManager.GetString("LabelFreqActiveChart01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活性歷史表(G) 的當地語系化字串。
        /// </summary>
        public static string LabelFreqActiveH {
            get {
                return ResourceManager.GetString("LabelFreqActiveH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活性歷史表單(G) 的當地語系化字串。
        /// </summary>
        public static string LabelFreqActiveHSingle {
            get {
                return ResourceManager.GetString("LabelFreqActiveHSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活性歷史總表(G) 的當地語系化字串。
        /// </summary>
        public static string LabelFreqActiveHT {
            get {
                return ResourceManager.GetString("LabelFreqActiveHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活性歷史總表01(G) 的當地語系化字串。
        /// </summary>
        public static string LabelFreqActiveHT01 {
            get {
                return ResourceManager.GetString("LabelFreqActiveHT01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活性歷史總表01(預載)(G) 的當地語系化字串。
        /// </summary>
        public static string LabelFreqActiveHT01P {
            get {
                return ResourceManager.GetString("LabelFreqActiveHT01P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活性歷史總表02(G) 的當地語系化字串。
        /// </summary>
        public static string LabelFreqActiveHT02 {
            get {
                return ResourceManager.GetString("LabelFreqActiveHT02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活性歷史總表All(G) 的當地語系化字串。
        /// </summary>
        public static string LabelFreqActiveHTAll {
            get {
                return ResourceManager.GetString("LabelFreqActiveHTAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 數字DNA(G) 的當地語系化字串。
        /// </summary>
        public static string LabelFreqDNA {
            get {
                return ResourceManager.GetString("LabelFreqDNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 DNA整合表(G) 的當地語系化字串。
        /// </summary>
        public static string LabelFreqDNAT {
            get {
                return ResourceManager.GetString("LabelFreqDNAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 頻率(G) 的當地語系化字串。
        /// </summary>
        public static string LabelFreqResult {
            get {
                return ResourceManager.GetString("LabelFreqResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 頻率單(G) 的當地語系化字串。
        /// </summary>
        public static string LabelFreqResultSingle {
            get {
                return ResourceManager.GetString("LabelFreqResultSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 頻率總表(G) 的當地語系化字串。
        /// </summary>
        public static string LabelFreqResultT {
            get {
                return ResourceManager.GetString("LabelFreqResultT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 數字區間(G) 的當地語系化字串。
        /// </summary>
        public static string LabelFreqSecField {
            get {
                return ResourceManager.GetString("LabelFreqSecField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 數字區間整合表(G) 的當地語系化字串。
        /// </summary>
        public static string LabelFreqSecFieldT {
            get {
                return ResourceManager.GetString("LabelFreqSecFieldT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 頻率組(G) 的當地語系化字串。
        /// </summary>
        public static string LabelFreqSet {
            get {
                return ResourceManager.GetString("LabelFreqSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 大-小數表(G) 的當地語系化字串。
        /// </summary>
        public static string LabelHighLow {
            get {
                return ResourceManager.GetString("LabelHighLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 遺漏表(G) 的當地語系化字串。
        /// </summary>
        public static string LabelMissingTotal {
            get {
                return ResourceManager.GetString("LabelMissingTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 遺漏整合表(G) 的當地語系化字串。
        /// </summary>
        public static string LabelMissingTotalT {
            get {
                return ResourceManager.GetString("LabelMissingTotalT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 遺漏整合表01(G) 的當地語系化字串。
        /// </summary>
        public static string LabelMissingTotalT01 {
            get {
                return ResourceManager.GetString("LabelMissingTotalT01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 奇-偶數表(G) 的當地語系化字串。
        /// </summary>
        public static string LabelOddEven {
            get {
                return ResourceManager.GetString("LabelOddEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 計算組合(G) 的當地語系化字串。
        /// </summary>
        public static string LabelSmartRun {
            get {
                return ResourceManager.GetString("LabelSmartRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聰明組合(G) 的當地語系化字串。
        /// </summary>
        public static string LabelSmartTest {
            get {
                return ResourceManager.GetString("LabelSmartTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 和數表(G) 的當地語系化字串。
        /// </summary>
        public static string LabelSum {
            get {
                return ResourceManager.GetString("LabelSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TP00(G) 的當地語系化字串。
        /// </summary>
        public static string LabelTablePercent {
            get {
                return ResourceManager.GetString("LabelTablePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TP01(G) 的當地語系化字串。
        /// </summary>
        public static string LabelTablePercent01 {
            get {
                return ResourceManager.GetString("LabelTablePercent01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TP02(G) 的當地語系化字串。
        /// </summary>
        public static string LabelTablePercent02 {
            get {
                return ResourceManager.GetString("LabelTablePercent02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 別名 的當地語系化字串。
        /// </summary>
        public static string lblCaption {
            get {
                return ResourceManager.GetString("lblCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料行 的當地語系化字串。
        /// </summary>
        public static string lblColumn {
            get {
                return ResourceManager.GetString("lblColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料型態 的當地語系化字串。
        /// </summary>
        public static string lblColumnDataType {
            get {
                return ResourceManager.GetString("lblColumnDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 樂　透 的當地語系化字串。
        /// </summary>
        public static string lblLottos {
            get {
                return ResourceManager.GetString("lblLottos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排序 的當地語系化字串。
        /// </summary>
        public static string lblSort {
            get {
                return ResourceManager.GetString("lblSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排序次序 的當地語系化字串。
        /// </summary>
        public static string lblSortOrder {
            get {
                return ResourceManager.GetString("lblSortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 篩選 的當地語系化字串。
        /// </summary>
        public static string lblWhere {
            get {
                return ResourceManager.GetString("lblWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N01 {
            get {
                object obj = ResourceManager.GetObject("N01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N02 {
            get {
                object obj = ResourceManager.GetObject("N02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N03 {
            get {
                object obj = ResourceManager.GetObject("N03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N04 {
            get {
                object obj = ResourceManager.GetObject("N04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N05 {
            get {
                object obj = ResourceManager.GetObject("N05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N06 {
            get {
                object obj = ResourceManager.GetObject("N06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N07 {
            get {
                object obj = ResourceManager.GetObject("N07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N08 {
            get {
                object obj = ResourceManager.GetObject("N08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N09 {
            get {
                object obj = ResourceManager.GetObject("N09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N10 {
            get {
                object obj = ResourceManager.GetObject("N10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N11 {
            get {
                object obj = ResourceManager.GetObject("N11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N12 {
            get {
                object obj = ResourceManager.GetObject("N12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N13 {
            get {
                object obj = ResourceManager.GetObject("N13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N14 {
            get {
                object obj = ResourceManager.GetObject("N14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N15 {
            get {
                object obj = ResourceManager.GetObject("N15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N16 {
            get {
                object obj = ResourceManager.GetObject("N16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N17 {
            get {
                object obj = ResourceManager.GetObject("N17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N18 {
            get {
                object obj = ResourceManager.GetObject("N18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N19 {
            get {
                object obj = ResourceManager.GetObject("N19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N20 {
            get {
                object obj = ResourceManager.GetObject("N20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N21 {
            get {
                object obj = ResourceManager.GetObject("N21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N22 {
            get {
                object obj = ResourceManager.GetObject("N22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N23 {
            get {
                object obj = ResourceManager.GetObject("N23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N24 {
            get {
                object obj = ResourceManager.GetObject("N24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N25 {
            get {
                object obj = ResourceManager.GetObject("N25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N26 {
            get {
                object obj = ResourceManager.GetObject("N26", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N27 {
            get {
                object obj = ResourceManager.GetObject("N27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N28 {
            get {
                object obj = ResourceManager.GetObject("N28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N29 {
            get {
                object obj = ResourceManager.GetObject("N29", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N30 {
            get {
                object obj = ResourceManager.GetObject("N30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N31 {
            get {
                object obj = ResourceManager.GetObject("N31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N32 {
            get {
                object obj = ResourceManager.GetObject("N32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N33 {
            get {
                object obj = ResourceManager.GetObject("N33", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N34 {
            get {
                object obj = ResourceManager.GetObject("N34", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N35 {
            get {
                object obj = ResourceManager.GetObject("N35", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N36 {
            get {
                object obj = ResourceManager.GetObject("N36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N37 {
            get {
                object obj = ResourceManager.GetObject("N37", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N38 {
            get {
                object obj = ResourceManager.GetObject("N38", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N39 {
            get {
                object obj = ResourceManager.GetObject("N39", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N40 {
            get {
                object obj = ResourceManager.GetObject("N40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N41 {
            get {
                object obj = ResourceManager.GetObject("N41", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N42 {
            get {
                object obj = ResourceManager.GetObject("N42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N43 {
            get {
                object obj = ResourceManager.GetObject("N43", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N44 {
            get {
                object obj = ResourceManager.GetObject("N44", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N45 {
            get {
                object obj = ResourceManager.GetObject("N45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N46 {
            get {
                object obj = ResourceManager.GetObject("N46", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N47 {
            get {
                object obj = ResourceManager.GetObject("N47", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N48 {
            get {
                object obj = ResourceManager.GetObject("N48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap N49 {
            get {
                object obj = ResourceManager.GetObject("N49", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        public static System.Drawing.Icon NetDrives {
            get {
                object obj = ResourceManager.GetObject("NetDrives", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 新增 的當地語系化字串。
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取消篩選 的當地語系化字串。
        /// </summary>
        public static string NoFilter {
            get {
                return ResourceManager.GetString("NoFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;optionsearch &gt;
        ///  &lt;!-- 年 --&gt;
        ///  &lt;item &gt;
        ///    &lt;name&gt;cmbWYear&lt;/name&gt;
        ///    &lt;rowsdata&gt;
        ///      &lt;id&gt;2002&lt;/id&gt;
        ///      &lt;description&gt;2002(91)&lt;/description&gt;
        ///      &lt;id&gt;2003&lt;/id&gt;
        ///      &lt;description&gt;2003(92)&lt;/description&gt;
        ///      &lt;id&gt;2004&lt;/id&gt;
        ///      &lt;description&gt;2004(93)&lt;/description&gt;
        ///      &lt;id&gt;2005&lt;/id&gt;
        ///      &lt;description&gt;2005(94)&lt;/description&gt;
        ///      &lt;id&gt;2006&lt;/id&gt;
        ///      &lt;description&gt;2006(95)&lt;/description&gt;
        ///      &lt;id&gt;2007&lt;/id&gt;
        ///      &lt;description&gt;2007(96)&lt;/description&gt;
        ///      &lt;id&gt;2008&lt;/id&gt;
        /// [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        public static string OptionPurple {
            get {
                return ResourceManager.GetString("OptionPurple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;optionsearch &gt;
        ///  &lt;!-- 彩別 --&gt;
        ///  &lt;item &gt;
        ///    &lt;name&gt;cmbLottoType&lt;/name&gt;
        ///    &lt;rowsdata&gt;
        ///      &lt;id&gt;Lotto539&lt;/id&gt;
        ///      &lt;description&gt;今彩539&lt;/description&gt;
        ///      &lt;id&gt;LottoBig&lt;/id&gt;
        ///      &lt;description&gt;大樂透&lt;/description&gt;
        ///      &lt;id&gt;LottoWeli&lt;/id&gt;
        ///      &lt;description&gt;威力彩&lt;/description&gt;
        ///      &lt;id&gt;LottoSix&lt;/id&gt;
        ///      &lt;description&gt;六合彩&lt;/description&gt;
        ///    &lt;/rowsdata&gt;
        ///  &lt;/item&gt;
        ///  &lt;!-- 比較方式 --&gt;
        ///  &lt;item&gt;
        ///    &lt;name &gt;cmbCompareType&lt;/name&gt;
        ///    &lt;rowsdata&gt;
        ///      &lt;id&gt;AND&lt;/id&gt;
        ///      &lt;description&gt;AND [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        public static string OptionSearch {
            get {
                return ResourceManager.GetString("OptionSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cacul01.aspx 的當地語系化字串。
        /// </summary>
        public static string PageCacul01 {
            get {
                return ResourceManager.GetString("PageCacul01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 DataB.aspx 的當地語系化字串。
        /// </summary>
        public static string PageDataB {
            get {
                return ResourceManager.GetString("PageDataB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 DataN.aspx 的當地語系化字串。
        /// </summary>
        public static string PageDataN {
            get {
                return ResourceManager.GetString("PageDataN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 DataNBT01.aspx 的當地語系化字串。
        /// </summary>
        public static string PageDataNBT01 {
            get {
                return ResourceManager.GetString("PageDataNBT01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 DataNChart.aspx 的當地語系化字串。
        /// </summary>
        public static string PageDataNChart {
            get {
                return ResourceManager.GetString("PageDataNChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FreqActive.aspx 的當地語系化字串。
        /// </summary>
        public static string PageFreqActive {
            get {
                return ResourceManager.GetString("PageFreqActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FreqActive01.aspx 的當地語系化字串。
        /// </summary>
        public static string PageFreqActive01 {
            get {
                return ResourceManager.GetString("PageFreqActive01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FreqActive01T.aspx 的當地語系化字串。
        /// </summary>
        public static string PageFreqActive01T {
            get {
                return ResourceManager.GetString("PageFreqActive01T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FreqActive01TR.aspx 的當地語系化字串。
        /// </summary>
        public static string PageFreqActive01TR {
            get {
                return ResourceManager.GetString("PageFreqActive01TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FreqActive02.aspx 的當地語系化字串。
        /// </summary>
        public static string PageFreqActive02 {
            get {
                return ResourceManager.GetString("PageFreqActive02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FreqActive03.aspx 的當地語系化字串。
        /// </summary>
        public static string PageFreqActive03 {
            get {
                return ResourceManager.GetString("PageFreqActive03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FreqActiveChart.aspx 的當地語系化字串。
        /// </summary>
        public static string PageFreqActiveChart {
            get {
                return ResourceManager.GetString("PageFreqActiveChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FreqActiveChart01.aspx 的當地語系化字串。
        /// </summary>
        public static string PageFreqActiveChart01 {
            get {
                return ResourceManager.GetString("PageFreqActiveChart01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FreqActiveH.aspx 的當地語系化字串。
        /// </summary>
        public static string PageFreqActiveH {
            get {
                return ResourceManager.GetString("PageFreqActiveH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FreqActiveHSingle.aspx 的當地語系化字串。
        /// </summary>
        public static string PageFreqActiveHSingle {
            get {
                return ResourceManager.GetString("PageFreqActiveHSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FreqActiveHT.aspx 的當地語系化字串。
        /// </summary>
        public static string PageFreqActiveHT {
            get {
                return ResourceManager.GetString("PageFreqActiveHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FreqActiveHT01.aspx 的當地語系化字串。
        /// </summary>
        public static string PageFreqActiveHT01 {
            get {
                return ResourceManager.GetString("PageFreqActiveHT01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FreqActiveHT01P.aspx 的當地語系化字串。
        /// </summary>
        public static string PageFreqActiveHT01P {
            get {
                return ResourceManager.GetString("PageFreqActiveHT01P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FreqActiveHT02.aspx 的當地語系化字串。
        /// </summary>
        public static string PageFreqActiveHT02 {
            get {
                return ResourceManager.GetString("PageFreqActiveHT02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FreqActiveHTAll.aspx 的當地語系化字串。
        /// </summary>
        public static string PageFreqActiveHTAll {
            get {
                return ResourceManager.GetString("PageFreqActiveHTAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FreqDNA.aspx 的當地語系化字串。
        /// </summary>
        public static string PageFreqDNA {
            get {
                return ResourceManager.GetString("PageFreqDNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FreqDNAT.aspx 的當地語系化字串。
        /// </summary>
        public static string PageFreqDNAT {
            get {
                return ResourceManager.GetString("PageFreqDNAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FreqResult.aspx 的當地語系化字串。
        /// </summary>
        public static string PageFreqResult {
            get {
                return ResourceManager.GetString("PageFreqResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FreqResultSingle.aspx 的當地語系化字串。
        /// </summary>
        public static string PageFreqResultSingle {
            get {
                return ResourceManager.GetString("PageFreqResultSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FreqResultT.aspx 的當地語系化字串。
        /// </summary>
        public static string PageFreqResultT {
            get {
                return ResourceManager.GetString("PageFreqResultT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FreqSecField.aspx 的當地語系化字串。
        /// </summary>
        public static string PageFreqSecField {
            get {
                return ResourceManager.GetString("PageFreqSecField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FreqSecFieldT.aspx 的當地語系化字串。
        /// </summary>
        public static string PageFreqSecFieldT {
            get {
                return ResourceManager.GetString("PageFreqSecFieldT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FreqSet.aspx 的當地語系化字串。
        /// </summary>
        public static string PageFreqSet {
            get {
                return ResourceManager.GetString("PageFreqSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MissingTotal.aspx 的當地語系化字串。
        /// </summary>
        public static string PageMissingTotal {
            get {
                return ResourceManager.GetString("PageMissingTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MissingTotalT.aspx 的當地語系化字串。
        /// </summary>
        public static string PageMissingTotalT {
            get {
                return ResourceManager.GetString("PageMissingTotalT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MissingTotalT01.aspx 的當地語系化字串。
        /// </summary>
        public static string PageMissingTotalT01 {
            get {
                return ResourceManager.GetString("PageMissingTotalT01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OddEven.aspx 的當地語系化字串。
        /// </summary>
        public static string PageOddEven {
            get {
                return ResourceManager.GetString("PageOddEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ShowAll.aspx 的當地語系化字串。
        /// </summary>
        public static string PageShowAll {
            get {
                return ResourceManager.GetString("PageShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SmartRun.aspx 的當地語系化字串。
        /// </summary>
        public static string PageSmartRun {
            get {
                return ResourceManager.GetString("PageSmartRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SmartTestResult.aspx 的當地語系化字串。
        /// </summary>
        public static string PageSmartTest {
            get {
                return ResourceManager.GetString("PageSmartTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SumResult.aspx 的當地語系化字串。
        /// </summary>
        public static string PageSum {
            get {
                return ResourceManager.GetString("PageSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TablePercent.aspx 的當地語系化字串。
        /// </summary>
        public static string PageTablePercent {
            get {
                return ResourceManager.GetString("PageTablePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TablePercent01.aspx 的當地語系化字串。
        /// </summary>
        public static string PageTablePercent01 {
            get {
                return ResourceManager.GetString("PageTablePercent01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TablePercent02.aspx 的當地語系化字串。
        /// </summary>
        public static string PageTablePercent02 {
            get {
                return ResourceManager.GetString("PageTablePercent02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream pause {
            get {
                return ResourceManager.GetStream("pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap planet {
            get {
                object obj = ResourceManager.GetObject("planet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        public static System.Drawing.Icon planet_asteroid {
            get {
                object obj = ResourceManager.GetObject("planet_asteroid", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        public static System.Drawing.Icon planet_blackhole {
            get {
                object obj = ResourceManager.GetObject("planet_blackhole", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        public static System.Drawing.Icon planet_earth {
            get {
                object obj = ResourceManager.GetObject("planet_earth", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        public static System.Drawing.Icon planet_jupiter {
            get {
                object obj = ResourceManager.GetObject("planet_jupiter", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        public static System.Drawing.Icon planet_mars {
            get {
                object obj = ResourceManager.GetObject("planet_mars", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        public static System.Drawing.Icon planet_mercury {
            get {
                object obj = ResourceManager.GetObject("planet_mercury", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        public static System.Drawing.Icon planet_moon {
            get {
                object obj = ResourceManager.GetObject("planet_moon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        public static System.Drawing.Icon planet_neptune {
            get {
                object obj = ResourceManager.GetObject("planet_neptune", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        public static System.Drawing.Icon planet_pluto {
            get {
                object obj = ResourceManager.GetObject("planet_pluto", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        public static System.Drawing.Icon planet_saturn {
            get {
                object obj = ResourceManager.GetObject("planet_saturn", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        public static System.Drawing.Icon planet_sun {
            get {
                object obj = ResourceManager.GetObject("planet_sun", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        public static System.Drawing.Icon planet_supernova {
            get {
                object obj = ResourceManager.GetObject("planet_supernova", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        public static System.Drawing.Icon planet_thanatos {
            get {
                object obj = ResourceManager.GetObject("planet_thanatos", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        public static System.Drawing.Icon planet_uranus {
            get {
                object obj = ResourceManager.GetObject("planet_uranus", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        public static System.Drawing.Icon planet_venus {
            get {
                object obj = ResourceManager.GetObject("planet_venus", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        public static System.Drawing.Icon planet1 {
            get {
                object obj = ResourceManager.GetObject("planet1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 重算 的當地語系化字串。
        /// </summary>
        public static string ReCaculate {
            get {
                return ResourceManager.GetString("ReCaculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 重載 的當地語系化字串。
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap scrollnew {
            get {
                object obj = ResourceManager.GetObject("scrollnew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        public static System.Drawing.Icon search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇 的當地語系化字串。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sCacul01 的當地語系化字串。
        /// </summary>
        public static string SessionsCacul01 {
            get {
                return ResourceManager.GetString("SessionsCacul01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sDataB 的當地語系化字串。
        /// </summary>
        public static string SessionsDataB {
            get {
                return ResourceManager.GetString("SessionsDataB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sDataN 的當地語系化字串。
        /// </summary>
        public static string SessionsDataN {
            get {
                return ResourceManager.GetString("SessionsDataN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sDataNBT01 的當地語系化字串。
        /// </summary>
        public static string SessionsDataNBT01 {
            get {
                return ResourceManager.GetString("SessionsDataNBT01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sDataNChart 的當地語系化字串。
        /// </summary>
        public static string SessionsDataNChart {
            get {
                return ResourceManager.GetString("SessionsDataNChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sFreqActive 的當地語系化字串。
        /// </summary>
        public static string SessionsFreqActive {
            get {
                return ResourceManager.GetString("SessionsFreqActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sFreqActive01 的當地語系化字串。
        /// </summary>
        public static string SessionsFreqActive01 {
            get {
                return ResourceManager.GetString("SessionsFreqActive01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sFreqActive01T 的當地語系化字串。
        /// </summary>
        public static string SessionsFreqActive01T {
            get {
                return ResourceManager.GetString("SessionsFreqActive01T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sFreqActive01TR 的當地語系化字串。
        /// </summary>
        public static string SessionsFreqActive01TR {
            get {
                return ResourceManager.GetString("SessionsFreqActive01TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sFreqActive02 的當地語系化字串。
        /// </summary>
        public static string SessionsFreqActive02 {
            get {
                return ResourceManager.GetString("SessionsFreqActive02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sFreqActive03 的當地語系化字串。
        /// </summary>
        public static string SessionsFreqActive03 {
            get {
                return ResourceManager.GetString("SessionsFreqActive03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sFreqActiveChart 的當地語系化字串。
        /// </summary>
        public static string SessionsFreqActiveChart {
            get {
                return ResourceManager.GetString("SessionsFreqActiveChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sFreqActiveChart01 的當地語系化字串。
        /// </summary>
        public static string SessionsFreqActiveChart01 {
            get {
                return ResourceManager.GetString("SessionsFreqActiveChart01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sFreqActiveH 的當地語系化字串。
        /// </summary>
        public static string SessionsFreqActiveH {
            get {
                return ResourceManager.GetString("SessionsFreqActiveH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sFreqActiveHSingle 的當地語系化字串。
        /// </summary>
        public static string SessionsFreqActiveHSingle {
            get {
                return ResourceManager.GetString("SessionsFreqActiveHSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sFreqActiveHT 的當地語系化字串。
        /// </summary>
        public static string SessionsFreqActiveHT {
            get {
                return ResourceManager.GetString("SessionsFreqActiveHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sFreqActiveHT01 的當地語系化字串。
        /// </summary>
        public static string SessionsFreqActiveHT01 {
            get {
                return ResourceManager.GetString("SessionsFreqActiveHT01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sFreqActiveHT01P 的當地語系化字串。
        /// </summary>
        public static string SessionsFreqActiveHT01P {
            get {
                return ResourceManager.GetString("SessionsFreqActiveHT01P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sFreqActiveHT02 的當地語系化字串。
        /// </summary>
        public static string SessionsFreqActiveHT02 {
            get {
                return ResourceManager.GetString("SessionsFreqActiveHT02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sFreqActiveHTAll 的當地語系化字串。
        /// </summary>
        public static string SessionsFreqActiveHTAll {
            get {
                return ResourceManager.GetString("SessionsFreqActiveHTAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sFreqDNA 的當地語系化字串。
        /// </summary>
        public static string SessionsFreqDNA {
            get {
                return ResourceManager.GetString("SessionsFreqDNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sFreqDNAT 的當地語系化字串。
        /// </summary>
        public static string SessionsFreqDNAT {
            get {
                return ResourceManager.GetString("SessionsFreqDNAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sFreqResult 的當地語系化字串。
        /// </summary>
        public static string SessionsFreqResult {
            get {
                return ResourceManager.GetString("SessionsFreqResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sFreqResultSingle 的當地語系化字串。
        /// </summary>
        public static string SessionsFreqResultSingle {
            get {
                return ResourceManager.GetString("SessionsFreqResultSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sFreqResultT 的當地語系化字串。
        /// </summary>
        public static string SessionsFreqResultT {
            get {
                return ResourceManager.GetString("SessionsFreqResultT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sFreqSecField 的當地語系化字串。
        /// </summary>
        public static string SessionsFreqSecField {
            get {
                return ResourceManager.GetString("SessionsFreqSecField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sFreqSecFieldT 的當地語系化字串。
        /// </summary>
        public static string SessionsFreqSecFieldT {
            get {
                return ResourceManager.GetString("SessionsFreqSecFieldT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sFreqSet 的當地語系化字串。
        /// </summary>
        public static string SessionsFreqSet {
            get {
                return ResourceManager.GetString("SessionsFreqSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sMissingTotal 的當地語系化字串。
        /// </summary>
        public static string SessionsMissingTotal {
            get {
                return ResourceManager.GetString("SessionsMissingTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sMissingTotalT 的當地語系化字串。
        /// </summary>
        public static string SessionsMissingTotalT {
            get {
                return ResourceManager.GetString("SessionsMissingTotalT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sMissingTotalT01 的當地語系化字串。
        /// </summary>
        public static string SessionsMissingTotalT01 {
            get {
                return ResourceManager.GetString("SessionsMissingTotalT01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sOddEven 的當地語系化字串。
        /// </summary>
        public static string SessionsOddEven {
            get {
                return ResourceManager.GetString("SessionsOddEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sShowAll 的當地語系化字串。
        /// </summary>
        public static string SessionsShowAll {
            get {
                return ResourceManager.GetString("SessionsShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sSmartRun 的當地語系化字串。
        /// </summary>
        public static string SessionsSmartRun {
            get {
                return ResourceManager.GetString("SessionsSmartRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sSmartTest 的當地語系化字串。
        /// </summary>
        public static string SessionsSmartTest {
            get {
                return ResourceManager.GetString("SessionsSmartTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sSum 的當地語系化字串。
        /// </summary>
        public static string SessionsSum {
            get {
                return ResourceManager.GetString("SessionsSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sTablePercent 的當地語系化字串。
        /// </summary>
        public static string SessionsTablePercent {
            get {
                return ResourceManager.GetString("SessionsTablePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sTP01 的當地語系化字串。
        /// </summary>
        public static string SessionsTablePercent01 {
            get {
                return ResourceManager.GetString("SessionsTablePercent01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sTP02 的當地語系化字串。
        /// </summary>
        public static string SessionsTablePercent02 {
            get {
                return ResourceManager.GetString("SessionsTablePercent02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 sUpdate 的當地語系化字串。
        /// </summary>
        public static string SessionsUpdate {
            get {
                return ResourceManager.GetString("SessionsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Six {
            get {
                object obj = ResourceManager.GetObject("Six", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap software_update {
            get {
                object obj = ResourceManager.GetObject("software_update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        public static System.Drawing.Icon software_update1 {
            get {
                object obj = ResourceManager.GetObject("software_update1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap spe {
            get {
                object obj = ResourceManager.GetObject("spe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 System.IO.MemoryStream 的類型 System.IO.UnmanagedMemoryStream 當地語系化資源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream startup {
            get {
                return ResourceManager.GetStream("startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [tblFreqSecHisFilter] 的當地語系化字串。
        /// </summary>
        public static string tblFreqSecHisFilter {
            get {
                return ResourceManager.GetString("tblFreqSecHisFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無 的當地語系化字串。
        /// </summary>
        public static string Unspecified {
            get {
                return ResourceManager.GetString("Unspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料處理中 ... 的當地語系化字串。
        /// </summary>
        public static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查看 的當地語系化字串。
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Web {
            get {
                object obj = ResourceManager.GetObject("Web", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        public static System.Drawing.Bitmap Weli {
            get {
                object obj = ResourceManager.GetObject("Weli", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 確定 的當地語系化字串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
